import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const AN_RGB_CCT_48V_90LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./AN_RGB_CCT_48V_90LPM.jpg", width: 417, height:30} as ImageDataType,
        technicalID: "AN_RGB_CCT_48V_90LPM",
        name: "compData.AN_RGB_CCT_48V_90LPM.name",
        description: "compData.AN_RGB_CCT_48V_90LPM.descriptionShort",
        popover: {
            description: "compData.AN_RGB_CCT_48V_90LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        handles: [
        {
            hid: "48V_start",
            type: "source",
            x: 2.5,
            y: 3,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "48V (+)",
            description: "+48V supply",
            prefferedLineDirection: "left",
            functions: ["suppl_in"],
            tolVmax: 48,
            tolVmin: 40,
        } as HandleDataType,
        {
            hid: "R_start",
            type: "source",
            x: 2.5,
            y: 8,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            prefferedLineDirection: "left",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_start",
            type: "source",
            x: 2.5,
            y: 13,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            prefferedLineDirection: "left",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_start",
            type: "source",
            x: 2.5,
            y: 17,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            prefferedLineDirection: "left",
            functions: ["pwm_in_B"],
        } as HandleDataType,
        {
            hid: "WW_start",
            type: "source",
            x: 2.5,
            y: 22,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "Warm White (-)",
            name: "Warm White",
            prefferedLineDirection: "left",
            functions: ["pwm_in_WW"],
        } as HandleDataType,
        {
            hid: "W_start",
            type: "source",
            x: 2.5,
            y: 27,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "White (-)",
            name: "White",
            prefferedLineDirection: "left",
            functions: ["pwm_in_W"],
        } as HandleDataType,
        
        {
            hid: "48V_end",
            type: "source",
            x: 2.5,
            y: 3,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "48V (+)",
            description: "+48V supply",
            prefferedLineDirection: "right",
            functions: ["suppl_in"],
            tolVmax: 48,
            tolVmin: 40,
        } as HandleDataType,
        {
            hid: "R_end",
            type: "source",
            x: 2.5,
            y: 8,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            prefferedLineDirection: "right",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_end",
            type: "source",
            x: 2.5,
            y: 13,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            prefferedLineDirection: "right",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_end",
            type: "source",
            x: 2.5,
            y: 17,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            prefferedLineDirection: "right",
            functions: ["pwm_in_B"],
        } as HandleDataType,
        {
            hid: "WW_end",
            type: "source",
            x: 2.5,
            y: 22,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "Warm White (-)",
            name: "Warm White",
            prefferedLineDirection: "right",
            functions: ["pwm_in_WW"],
        } as HandleDataType,
        {
            hid: "W_end",
            type: "source",
            x: 2.5,
            y: 27,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "White (-)",
            name: "White",
            prefferedLineDirection: "right",
            functions: ["pwm_in_W"],
        } as HandleDataType,
        {
            hid: "48V_middle",
            type: "source",
            x: 0,
            y: 3,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "48V (+)",
            description: "+48V supply",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["suppl_in"],
            tolVmax: 48,
            tolVmin: 40,
        } as HandleDataType,
        {
            hid: "R_middle",
            type: "source",
            x: 0,
            y: 8,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_middle",
            type: "source",
            x: 0,
            y: 13,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_middle",
            type: "source",
            x: 0,
            y: 17,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_B"],
        } as HandleDataType,
        {
            hid: "WW_middle",
            type: "source",
            x: 0,
            y: 22,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "Warm White (-)",
            name: "Warm White",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_WW"],
        } as HandleDataType,
        {
            hid: "W_middle",
            type: "source",
            x: 0,
            y: 27,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "White (-)",
            name: "White",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_W"],
        } as HandleDataType,
        ]
    } as ComponentDataType,
}



