import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const AN_RGB_24V_120LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./AN_RGB_24V_120LPM.jpg", width: 125, height:25} as ImageDataType,
        technicalID: "AN_RGB_24V_120LPM",
        name: "compData.AN_RGB_24V_120LPM.name",
        description: "compData.AN_RGB_24V_120LPM.descriptionShort",
        popover: {
            description: "compData.AN_RGB_24V_120LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        handles: [
        {
            hid: "24V_start",
            type: "source",
            x: 2.5,
            y: 3,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V (+)",
            description: "+24V supply",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "R_start",
            type: "source",
            x: 2.5,
            y: 9,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            prefferedLineDirection: "left",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_start",
            type: "source",
            x: 2.5,
            y: 15,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            prefferedLineDirection: "left",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_start",
            type: "source",
            x: 2.5,
            y: 21,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            prefferedLineDirection: "left",
            functions: ["pwm_in_B"],
        } as HandleDataType,        
        {
            hid: "24V_end",
            type: "source",
            x: 2.5,
            y: 3,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V (+)",
            description: "+24V supply",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "R_end",
            type: "source",
            x: 2.5,
            y: 9,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            prefferedLineDirection: "right",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_end",
            type: "source",
            x: 2.5,
            y: 15,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            prefferedLineDirection: "right",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_end",
            type: "source",
            x: 2.5,
            y: 21,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            prefferedLineDirection: "right",
            functions: ["pwm_in_B"],
        } as HandleDataType,
        {
            hid: "24V_middle",
            type: "source",
            x: 0,
            y: 3,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V (+)",
            description: "+24V supply",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "R_middle",
            type: "source",
            x: 0,
            y: 9,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "RED (-)",
            name: "RED",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_R"],
        } as HandleDataType,
        {
            hid: "G_middle",
            type: "source",
            x: 0,
            y: 15,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GREEN (-)",
            name: "GREEN",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_G"],
        } as HandleDataType,
        {
            hid: "B_middle",
            type: "source",
            x: 0,
            y: 21,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "BLUE (-)",
            name: "BLUE",
            repeated: "yes",
            repeatAtFirst: "no",
            functions: ["pwm_in_B"],
        } as HandleDataType,
        ]
    } as ComponentDataType,
}



