import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const WS2814_24V_60LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./WS2814_24V_60LPM.png", width: 253, height: 25} as ImageDataType,
        technicalID: "WS2814_24V_60LPM",
        name: "compData.WS2814_24V_60LPM.name",
        description: "compData.WS2814_24V_60LPM.descriptionShort",
        popover: {
            description: "compData.WS2814_24V_60LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        simdata: {
            version: 1,
            elements: [
                {
                    id: "strip-led",
                    type: "digitalLed",
                    terminals: {
                        supplyIn: "24V_start",
                        supplyOut: "24V_end",
                        gndIn: "GND_start",
                        gndOut: "GND_end",
                    },
                    parameters: {
                        supplyResistanceOhm: 0.002,
                        gndResistanceOhm: 0.002,
                        ledType: "WS2814_24V",
                        ledsPerMeter: 60,
                        physLedsPerLogicLed: 6,
                        currentLookup: {
                            ledLookup: "WS2814_24V",
                            colorMode: "settings.ledColorMode",
                        },
                    },
                },
            ],
        },
        handles: [
        {
            hid: "24V_start",
            type: "source",
            x: 2.7,
            y: 4.35,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 6,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "DATA_start",
            mustBeConnected: true,
            type: "source",
            x: 2.7,
            y: 12,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 6,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA input",
            functions: ["dig_in"],
            prefferedLineDirection: "left",
            tolVmin: 4.5,
            tolVmax: 5,
        } as HandleDataType,
        {
            hid: "GND_start",
            type: "source",
            x: 2.7,
            y: 19.5,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 4,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            functions: ["gnd"],
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "24V_end",
            type: "source",
            x: 2.7,
            y: 4.35,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 6,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "DATA_end",
            type: "source",
            x: 2.7,
            y: 12,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 6,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA output",
            functions: ["dig_out"],
            prefferedLineDirection: "right",
            Vout: 5,
        } as HandleDataType,
        {
            hid: "GND_end",
            type: "source",
            x: 2.7,
            y: 19.5,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 4,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            functions: ["gnd"],
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "24V_middle",
            type: "source",
            x: 0,
            y: 4.35,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 6,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            functions: ["suppl_in"],
            tolVmin: 20,
            tolVmax: 24,
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "DATA_middle",
            type: "source",
            x: 0,
            y: 12,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 6,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA",
            functions: ["not_connected"],
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "GND_middle",
            type: "source",
            x: 0,
            y: 19.5,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 6,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GND",
            name: "GND pin",
            functions: ["gnd"],
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        ]
    } as ComponentDataType,
}



