import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const WS2815_12V_30LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./WS2815_12V_30LPM.png", width: 85, height: 25} as ImageDataType,
        technicalID: "WS2815_12V_30LPM",
        name: "compData.WS2815_12V_30LPM.name",
        description: "compData.WS2815_12V_30LPM.descriptionShort",
        popover: {
            description: "compData.WS2815_12V_30LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        handles: [
        {
            hid: "12V_start",
            type: "source",
            x: 2.7,
            y: 22.4,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "12V pin",
            description: "12V supply input",
            functions: ["suppl_in"],
            tolVmin: 10,
            tolVmax: 12,
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "BACKUP_start",
            mustBeConnected: true,
            type: "source",
            x: 2.7,
            y: 9.6,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "Must be tied to GND",
            name: "Backup input",
            functions: ["dig_backup_in"],
            prefferedLineDirection: "left",
            tolVmin: 4.5,
            tolVmax: 5,
        } as HandleDataType,
        {
            hid: "DATA_start",
            mustBeConnected: true,
            type: "source",
            x: 2.7,
            y: 16,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA input",
            functions: ["dig_in"],
            prefferedLineDirection: "left",
            tolVmin: 4.5,
            tolVmax: 5,
        } as HandleDataType,
        {
            hid: "GND_start",
            type: "source",
            x: 2.7,
            y: 3.2,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            functions: ["gnd"],
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "12V_end",
            type: "source",
            x: 2.7,
            y: 22.4,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "12V pin",
            description: "12V supply input",
            functions: ["suppl_in"],
            tolVmin: 10,
            tolVmax: 12,
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "BACKUP_end",
            type: "source",
            x: 2.7,
            y: 9.6,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "Backup output",
            functions: ["dig_backup_out"],
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "DATA_end",
            type: "source",
            x: 2.7,
            y: 16,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA output",
            functions: ["dig_out"],
            prefferedLineDirection: "right",
            Vout: 5,
        } as HandleDataType,
        {
            hid: "GND_end",
            type: "source",
            x: 2.7,
            y: 3.2,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            functions: ["gnd"],
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "12V_middle",
            type: "source",
            x: 0,
            y: 22.4,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "12V pin",
            description: "12V supply input",
            functions: ["suppl_in"],
            tolVmin: 10,
            tolVmax: 12,
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "BACKUP_middle",
            type: "source",
            x: 0,
            y: 9.6,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "Must be tied to GND",
            name: "Backup",
            functions: ["not_connected"],
        } as HandleDataType,
        {
            hid: "DATA_middle",
            type: "source",
            x: 0,
            y: 16,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA",
            functions: ["not_connected"],
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "GND_middle",
            type: "source",
            x: 0,
            y: 3.2,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GND",
            name: "GND pin",
            functions: ["gnd"],
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        ]
    } as ComponentDataType,
}




